/* Class name: ProgressForm
 * File name:  ProgressForm.java
 * Project:    Open Document and Information Network (Odin)
 ** Copyright:  © 2007-2012 Alexander J. Harris, all rights reserved
 * Created:    31-Mar-2011 17:28:27
 * Modified:   31-Mar-2011
 *
 * Version History:
 * ~ ~ ~ ~ ~ ~ ~ ~ ~
 * 0.001  31-Mar-2011 Initial build
 */

package odin.sleipnir;

import java.util.ResourceBundle;

/**
 * JavaDoc to follow.
 * @version 0.001
 * @author Alexander J. Harris (email: Alexander.J.Harris(at)btinternet.com)
 */
public class ProgressForm extends javax.swing.JInternalFrame
{
  private ResourceBundle rbUser;

    /** Creates new form ProgressForm */
    public ProgressForm(ResourceBundle rb) {
      super("Working",true,true,true,true);
      super.setLayer(10);
      rbUser = rb;
      initComponents();
      MainWindow mw = MainWindow.getMainWindow();
      mw.addToDesktop(this);
      this.setVisible(true);
      this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlStatus = new javax.swing.JLabel();
        jpbProgress = new javax.swing.JProgressBar();

        setTitle(rbUser.getString("gui.progress.title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jlStatus.setText("Status");
        getContentPane().add(jlStatus);
        getContentPane().add(jpbProgress);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setStatus(String newStatus)
    {
      jlStatus.setText(newStatus);
    }

    public void closeWindow()
    {
      this.setVisible(false);
    }

    public void setProgress(int max)
    {
      jpbProgress.setValue(0);
      jpbProgress.setMaximum(max);
    }

    public void increaseProgress()
    {
      jpbProgress.setValue(jpbProgress.getValue() + 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlStatus;
    private javax.swing.JProgressBar jpbProgress;
    // End of variables declaration//GEN-END:variables

}
