//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 03:36:22 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sites.google.com/site/printmiles/Odin", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package odin.shared.xml;
