//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 03:36:23 PM BST 
//


package odin.odin.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the odin.odin.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: odin.odin.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Item.Location }
     * 
     */
    public Item.Location createItemLocation() {
        return new Item.Location();
    }

    /**
     * Create an instance of {@link Item.Origin }
     * 
     */
    public Item.Origin createItemOrigin() {
        return new Item.Origin();
    }

    /**
     * Create an instance of {@link Rules.Rule.Convert.From }
     * 
     */
    public Rules.Rule.Convert.From createRulesRuleConvertFrom() {
        return new Rules.Rule.Convert.From();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Propogation.Path }
     * 
     */
    public odin.odin.xml.Rule.Propogation.Path createRulePropogationPath() {
        return new odin.odin.xml.Rule.Propogation.Path();
    }

    /**
     * Create an instance of {@link Root.Policies.Zip }
     * 
     */
    public Root.Policies.Zip createRootPoliciesZip() {
        return new Root.Policies.Zip();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link Item.Location.Archive }
     * 
     */
    public Item.Location.Archive createItemLocationArchive() {
        return new Item.Location.Archive();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Propogation }
     * 
     */
    public odin.odin.xml.Rule.Propogation createRulePropogation() {
        return new odin.odin.xml.Rule.Propogation();
    }

    /**
     * Create an instance of {@link Report.Reports }
     * 
     */
    public Report.Reports createReportReports() {
        return new Report.Reports();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Propogation.Path.Node }
     * 
     */
    public odin.odin.xml.Rule.Propogation.Path.Node createRulePropogationPathNode() {
        return new odin.odin.xml.Rule.Propogation.Path.Node();
    }

    /**
     * Create an instance of {@link Item.Attributes }
     * 
     */
    public Item.Attributes createItemAttributes() {
        return new Item.Attributes();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Convert.To }
     * 
     */
    public odin.odin.xml.Rule.Convert.To createRuleConvertTo() {
        return new odin.odin.xml.Rule.Convert.To();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Status.Active }
     * 
     */
    public odin.odin.xml.Rule.Status.Active createRuleStatusActive() {
        return new odin.odin.xml.Rule.Status.Active();
    }

    /**
     * Create an instance of {@link Item.Keywords }
     * 
     */
    public Item.Keywords createItemKeywords() {
        return new Item.Keywords();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Contact }
     * 
     */
    public odin.odin.xml.Rule.Contact createRuleContact() {
        return new odin.odin.xml.Rule.Contact();
    }

    /**
     * Create an instance of {@link Permission }
     * 
     */
    public Permission createPermission() {
        return new Permission();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link AddedDetails }
     * 
     */
    public AddedDetails createAddedDetails() {
        return new AddedDetails();
    }

    /**
     * Create an instance of {@link Item.Location.Repository }
     * 
     */
    public Item.Location.Repository createItemLocationRepository() {
        return new Item.Location.Repository();
    }

    /**
     * Create an instance of {@link Rules.Rule.Convert }
     * 
     */
    public Rules.Rule.Convert createRulesRuleConvert() {
        return new Rules.Rule.Convert();
    }

    /**
     * Create an instance of {@link Root.Details }
     * 
     */
    public Root.Details createRootDetails() {
        return new Root.Details();
    }

    /**
     * Create an instance of {@link Rules.Rule.Convert.To }
     * 
     */
    public Rules.Rule.Convert.To createRulesRuleConvertTo() {
        return new Rules.Rule.Convert.To();
    }

    /**
     * Create an instance of {@link Rules.Rule }
     * 
     */
    public Rules.Rule createRulesRule() {
        return new Rules.Rule();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Item.Origin.Author }
     * 
     */
    public Item.Origin.Author createItemOriginAuthor() {
        return new Item.Origin.Author();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule }
     * 
     */
    public odin.odin.xml.Rule createRule() {
        return new odin.odin.xml.Rule();
    }

    /**
     * Create an instance of {@link Entries.Entry }
     * 
     */
    public Entries.Entry createEntriesEntry() {
        return new Entries.Entry();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Status }
     * 
     */
    public odin.odin.xml.Rule.Status createRuleStatus() {
        return new odin.odin.xml.Rule.Status();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Repository }
     * 
     */
    public odin.odin.xml.Repository createRepository() {
        return new odin.odin.xml.Repository();
    }

    /**
     * Create an instance of {@link Rules.Rule.Propogation }
     * 
     */
    public Rules.Rule.Propogation createRulesRulePropogation() {
        return new Rules.Rule.Propogation();
    }

    /**
     * Create an instance of {@link Root.Policies.Repository.Database }
     * 
     */
    public Root.Policies.Repository.Database createRootPoliciesRepositoryDatabase() {
        return new Root.Policies.Repository.Database();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Report.Summary }
     * 
     */
    public Report.Summary createReportSummary() {
        return new Report.Summary();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Type.Xml }
     * 
     */
    public odin.odin.xml.Rule.Type.Xml createRuleTypeXml() {
        return new odin.odin.xml.Rule.Type.Xml();
    }

    /**
     * Create an instance of {@link Permission.Order }
     * 
     */
    public Permission.Order createPermissionOrder() {
        return new Permission.Order();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Type }
     * 
     */
    public odin.odin.xml.Rule.Type createRuleType() {
        return new odin.odin.xml.Rule.Type();
    }

    /**
     * Create an instance of {@link Entries }
     * 
     */
    public Entries createEntries() {
        return new Entries();
    }

    /**
     * Create an instance of {@link Root.Subjects }
     * 
     */
    public Root.Subjects createRootSubjects() {
        return new Root.Subjects();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Version }
     * 
     */
    public odin.odin.xml.Rule.Version createRuleVersion() {
        return new odin.odin.xml.Rule.Version();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Convert }
     * 
     */
    public odin.odin.xml.Rule.Convert createRuleConvert() {
        return new odin.odin.xml.Rule.Convert();
    }

    /**
     * Create an instance of {@link Item.Origin.Locale }
     * 
     */
    public Item.Origin.Locale createItemOriginLocale() {
        return new Item.Origin.Locale();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Status.Active.Lastrun }
     * 
     */
    public odin.odin.xml.Rule.Status.Active.Lastrun createRuleStatusActiveLastrun() {
        return new odin.odin.xml.Rule.Status.Active.Lastrun();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Repository.Keywords }
     * 
     */
    public odin.odin.xml.Repository.Keywords createRepositoryKeywords() {
        return new odin.odin.xml.Repository.Keywords();
    }

    /**
     * Create an instance of {@link odin.odin.xml.Rule.Convert.From }
     * 
     */
    public odin.odin.xml.Rule.Convert.From createRuleConvertFrom() {
        return new odin.odin.xml.Rule.Convert.From();
    }

    /**
     * Create an instance of {@link Root.Policies.Xml }
     * 
     */
    public Root.Policies.Xml createRootPoliciesXml() {
        return new Root.Policies.Xml();
    }

    /**
     * Create an instance of {@link Root.Policies.Trust }
     * 
     */
    public Root.Policies.Trust createRootPoliciesTrust() {
        return new Root.Policies.Trust();
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link Root.Locations }
     * 
     */
    public Root.Locations createRootLocations() {
        return new Root.Locations();
    }

    /**
     * Create an instance of {@link Root.Policies }
     * 
     */
    public Root.Policies createRootPolicies() {
        return new Root.Policies();
    }

    /**
     * Create an instance of {@link Item.Attributes.Attribute }
     * 
     */
    public Item.Attributes.Attribute createItemAttributesAttribute() {
        return new Item.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link Rules.Rule.Version }
     * 
     */
    public Rules.Rule.Version createRulesRuleVersion() {
        return new Rules.Rule.Version();
    }

    /**
     * Create an instance of {@link Root.Policies.Repository }
     * 
     */
    public Root.Policies.Repository createRootPoliciesRepository() {
        return new Root.Policies.Repository();
    }

}
