//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 03:36:23 PM BST 
//


package odin.odin.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="summary">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numberOfFiles" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="lastUpdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reports">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fileType" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
 *                   &lt;element name="mimeType" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
 *                   &lt;element name="country" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
 *                   &lt;element name="language" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
 *                   &lt;element name="author" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
 *                   &lt;element name="organisation" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
 *                   &lt;element name="submitted" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
 *                   &lt;element name="trust" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "summary",
    "reports"
})
@XmlRootElement(name = "report")
public class Report {

    @XmlElement(required = true)
    protected Report.Summary summary;
    @XmlElement(required = true)
    protected Report.Reports reports;

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link Report.Summary }
     *     
     */
    public Report.Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Report.Summary }
     *     
     */
    public void setSummary(Report.Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the reports property.
     * 
     * @return
     *     possible object is
     *     {@link Report.Reports }
     *     
     */
    public Report.Reports getReports() {
        return reports;
    }

    /**
     * Sets the value of the reports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Report.Reports }
     *     
     */
    public void setReports(Report.Reports value) {
        this.reports = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fileType" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
     *         &lt;element name="mimeType" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
     *         &lt;element name="country" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
     *         &lt;element name="language" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
     *         &lt;element name="author" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
     *         &lt;element name="organisation" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
     *         &lt;element name="submitted" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
     *         &lt;element name="trust" type="{http://sites.google.com/site/printmiles/Odin}entries"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fileType",
        "mimeType",
        "country",
        "language",
        "author",
        "organisation",
        "submitted",
        "trust"
    })
    public static class Reports {

        @XmlElement(required = true)
        protected Entries fileType;
        @XmlElement(required = true)
        protected Entries mimeType;
        @XmlElement(required = true)
        protected Entries country;
        @XmlElement(required = true)
        protected Entries language;
        @XmlElement(required = true)
        protected Entries author;
        @XmlElement(required = true)
        protected Entries organisation;
        @XmlElement(required = true)
        protected Entries submitted;
        @XmlElement(required = true)
        protected Entries trust;

        /**
         * Gets the value of the fileType property.
         * 
         * @return
         *     possible object is
         *     {@link Entries }
         *     
         */
        public Entries getFileType() {
            return fileType;
        }

        /**
         * Sets the value of the fileType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entries }
         *     
         */
        public void setFileType(Entries value) {
            this.fileType = value;
        }

        /**
         * Gets the value of the mimeType property.
         * 
         * @return
         *     possible object is
         *     {@link Entries }
         *     
         */
        public Entries getMimeType() {
            return mimeType;
        }

        /**
         * Sets the value of the mimeType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entries }
         *     
         */
        public void setMimeType(Entries value) {
            this.mimeType = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link Entries }
         *     
         */
        public Entries getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entries }
         *     
         */
        public void setCountry(Entries value) {
            this.country = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link Entries }
         *     
         */
        public Entries getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entries }
         *     
         */
        public void setLanguage(Entries value) {
            this.language = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link Entries }
         *     
         */
        public Entries getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entries }
         *     
         */
        public void setAuthor(Entries value) {
            this.author = value;
        }

        /**
         * Gets the value of the organisation property.
         * 
         * @return
         *     possible object is
         *     {@link Entries }
         *     
         */
        public Entries getOrganisation() {
            return organisation;
        }

        /**
         * Sets the value of the organisation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entries }
         *     
         */
        public void setOrganisation(Entries value) {
            this.organisation = value;
        }

        /**
         * Gets the value of the submitted property.
         * 
         * @return
         *     possible object is
         *     {@link Entries }
         *     
         */
        public Entries getSubmitted() {
            return submitted;
        }

        /**
         * Sets the value of the submitted property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entries }
         *     
         */
        public void setSubmitted(Entries value) {
            this.submitted = value;
        }

        /**
         * Gets the value of the trust property.
         * 
         * @return
         *     possible object is
         *     {@link Entries }
         *     
         */
        public Entries getTrust() {
            return trust;
        }

        /**
         * Sets the value of the trust property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entries }
         *     
         */
        public void setTrust(Entries value) {
            this.trust = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numberOfFiles" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="lastUpdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numberOfFiles",
        "lastUpdate"
    })
    public static class Summary {

        @XmlElement(required = true)
        protected BigInteger numberOfFiles;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar lastUpdate;

        /**
         * Gets the value of the numberOfFiles property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfFiles() {
            return numberOfFiles;
        }

        /**
         * Sets the value of the numberOfFiles property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfFiles(BigInteger value) {
            this.numberOfFiles = value;
        }

        /**
         * Gets the value of the lastUpdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastUpdate() {
            return lastUpdate;
        }

        /**
         * Sets the value of the lastUpdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLastUpdate(XMLGregorianCalendar value) {
            this.lastUpdate = value;
        }

    }

}
