//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 03:36:23 PM BST 
//


package odin.odin.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subjects">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="details">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="adminName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="policies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="repository">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="xml" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="database">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="connection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="pw" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="zip">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="store" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="extract" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="xml">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="namespace" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="trust">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="accept" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="locations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="archive" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="conversion" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="logging" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="preference" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="quarantine" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="repository" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="security" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subjects",
    "details",
    "policies",
    "locations"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(required = true)
    protected Root.Subjects subjects;
    @XmlElement(required = true)
    protected Root.Details details;
    @XmlElement(required = true)
    protected Root.Policies policies;
    @XmlElement(required = true)
    protected Root.Locations locations;

    /**
     * Gets the value of the subjects property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Subjects }
     *     
     */
    public Root.Subjects getSubjects() {
        return subjects;
    }

    /**
     * Sets the value of the subjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Subjects }
     *     
     */
    public void setSubjects(Root.Subjects value) {
        this.subjects = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Details }
     *     
     */
    public Root.Details getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Details }
     *     
     */
    public void setDetails(Root.Details value) {
        this.details = value;
    }

    /**
     * Gets the value of the policies property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Policies }
     *     
     */
    public Root.Policies getPolicies() {
        return policies;
    }

    /**
     * Sets the value of the policies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Policies }
     *     
     */
    public void setPolicies(Root.Policies value) {
        this.policies = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Locations }
     *     
     */
    public Root.Locations getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Locations }
     *     
     */
    public void setLocations(Root.Locations value) {
        this.locations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="adminName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serverName",
        "website",
        "email",
        "phone",
        "adminName"
    })
    public static class Details {

        @XmlElement(required = true)
        protected String serverName;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String website;
        @XmlElement(required = true)
        protected String email;
        @XmlElement(required = true)
        protected String phone;
        @XmlElement(required = true)
        protected String adminName;

        /**
         * Gets the value of the serverName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerName() {
            return serverName;
        }

        /**
         * Sets the value of the serverName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerName(String value) {
            this.serverName = value;
        }

        /**
         * Gets the value of the website property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebsite() {
            return website;
        }

        /**
         * Sets the value of the website property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebsite(String value) {
            this.website = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the phone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhone() {
            return phone;
        }

        /**
         * Sets the value of the phone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhone(String value) {
            this.phone = value;
        }

        /**
         * Gets the value of the adminName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdminName() {
            return adminName;
        }

        /**
         * Sets the value of the adminName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdminName(String value) {
            this.adminName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="archive" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="conversion" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="logging" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="preference" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="quarantine" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="repository" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="security" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Locations {

        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String archive;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String conversion;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String format;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String logging;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String preference;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String quarantine;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String repository;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String security;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String report;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String barcode;

        /**
         * Gets the value of the archive property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArchive() {
            return archive;
        }

        /**
         * Sets the value of the archive property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArchive(String value) {
            this.archive = value;
        }

        /**
         * Gets the value of the conversion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConversion() {
            return conversion;
        }

        /**
         * Sets the value of the conversion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConversion(String value) {
            this.conversion = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

        /**
         * Gets the value of the logging property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogging() {
            return logging;
        }

        /**
         * Sets the value of the logging property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogging(String value) {
            this.logging = value;
        }

        /**
         * Gets the value of the preference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreference() {
            return preference;
        }

        /**
         * Sets the value of the preference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreference(String value) {
            this.preference = value;
        }

        /**
         * Gets the value of the quarantine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQuarantine() {
            return quarantine;
        }

        /**
         * Sets the value of the quarantine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQuarantine(String value) {
            this.quarantine = value;
        }

        /**
         * Gets the value of the repository property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRepository() {
            return repository;
        }

        /**
         * Sets the value of the repository property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRepository(String value) {
            this.repository = value;
        }

        /**
         * Gets the value of the security property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecurity() {
            return security;
        }

        /**
         * Sets the value of the security property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecurity(String value) {
            this.security = value;
        }

        /**
         * Gets the value of the report property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReport() {
            return report;
        }

        /**
         * Sets the value of the report property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReport(String value) {
            this.report = value;
        }

        /**
         * Gets the value of the barcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBarcode() {
            return barcode;
        }

        /**
         * Sets the value of the barcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBarcode(String value) {
            this.barcode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="repository">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="xml" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="database">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="connection" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="pw" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="zip">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="store" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="extract" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="xml">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="namespace" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="trust">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="accept" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Policies {

        @XmlElement(required = true)
        protected Root.Policies.Repository repository;
        @XmlElement(required = true)
        protected Root.Policies.Zip zip;
        @XmlElement(required = true)
        protected Root.Policies.Xml xml;
        @XmlElement(required = true)
        protected Root.Policies.Trust trust;

        /**
         * Gets the value of the repository property.
         * 
         * @return
         *     possible object is
         *     {@link Root.Policies.Repository }
         *     
         */
        public Root.Policies.Repository getRepository() {
            return repository;
        }

        /**
         * Sets the value of the repository property.
         * 
         * @param value
         *     allowed object is
         *     {@link Root.Policies.Repository }
         *     
         */
        public void setRepository(Root.Policies.Repository value) {
            this.repository = value;
        }

        /**
         * Gets the value of the zip property.
         * 
         * @return
         *     possible object is
         *     {@link Root.Policies.Zip }
         *     
         */
        public Root.Policies.Zip getZip() {
            return zip;
        }

        /**
         * Sets the value of the zip property.
         * 
         * @param value
         *     allowed object is
         *     {@link Root.Policies.Zip }
         *     
         */
        public void setZip(Root.Policies.Zip value) {
            this.zip = value;
        }

        /**
         * Gets the value of the xml property.
         * 
         * @return
         *     possible object is
         *     {@link Root.Policies.Xml }
         *     
         */
        public Root.Policies.Xml getXml() {
            return xml;
        }

        /**
         * Sets the value of the xml property.
         * 
         * @param value
         *     allowed object is
         *     {@link Root.Policies.Xml }
         *     
         */
        public void setXml(Root.Policies.Xml value) {
            this.xml = value;
        }

        /**
         * Gets the value of the trust property.
         * 
         * @return
         *     possible object is
         *     {@link Root.Policies.Trust }
         *     
         */
        public Root.Policies.Trust getTrust() {
            return trust;
        }

        /**
         * Sets the value of the trust property.
         * 
         * @param value
         *     allowed object is
         *     {@link Root.Policies.Trust }
         *     
         */
        public void setTrust(Root.Policies.Trust value) {
            this.trust = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="xml" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="database">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="connection" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="pw" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "xml",
            "database"
        })
        public static class Repository {

            protected Boolean xml;
            protected Root.Policies.Repository.Database database;

            /**
             * Gets the value of the xml property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isXml() {
                return xml;
            }

            /**
             * Sets the value of the xml property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setXml(Boolean value) {
                this.xml = value;
            }

            /**
             * Gets the value of the database property.
             * 
             * @return
             *     possible object is
             *     {@link Root.Policies.Repository.Database }
             *     
             */
            public Root.Policies.Repository.Database getDatabase() {
                return database;
            }

            /**
             * Sets the value of the database property.
             * 
             * @param value
             *     allowed object is
             *     {@link Root.Policies.Repository.Database }
             *     
             */
            public void setDatabase(Root.Policies.Repository.Database value) {
                this.database = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="connection" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="pw" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class Database {

                @XmlElement(required = true)
                protected String driver;
                @XmlElement(required = true)
                protected String connection;
                @XmlElement(required = true)
                protected String user;
                @XmlElement(required = true)
                protected String pw;

                /**
                 * Gets the value of the driver property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDriver() {
                    return driver;
                }

                /**
                 * Sets the value of the driver property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDriver(String value) {
                    this.driver = value;
                }

                /**
                 * Gets the value of the connection property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConnection() {
                    return connection;
                }

                /**
                 * Sets the value of the connection property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConnection(String value) {
                    this.connection = value;
                }

                /**
                 * Gets the value of the user property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUser() {
                    return user;
                }

                /**
                 * Sets the value of the user property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUser(String value) {
                    this.user = value;
                }

                /**
                 * Gets the value of the pw property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPw() {
                    return pw;
                }

                /**
                 * Sets the value of the pw property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPw(String value) {
                    this.pw = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="accept" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Trust {

            @XmlElement(required = true)
            protected BigInteger reject;
            @XmlElement(required = true)
            protected BigInteger accept;

            /**
             * Gets the value of the reject property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getReject() {
                return reject;
            }

            /**
             * Sets the value of the reject property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setReject(BigInteger value) {
                this.reject = value;
            }

            /**
             * Gets the value of the accept property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAccept() {
                return accept;
            }

            /**
             * Sets the value of the accept property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAccept(BigInteger value) {
                this.accept = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="namespace" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reject",
            "all",
            "namespace"
        })
        public static class Xml {

            protected Boolean reject;
            protected Boolean all;
            protected Boolean namespace;

            /**
             * Gets the value of the reject property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isReject() {
                return reject;
            }

            /**
             * Sets the value of the reject property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setReject(Boolean value) {
                this.reject = value;
            }

            /**
             * Gets the value of the all property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAll() {
                return all;
            }

            /**
             * Sets the value of the all property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAll(Boolean value) {
                this.all = value;
            }

            /**
             * Gets the value of the namespace property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isNamespace() {
                return namespace;
            }

            /**
             * Sets the value of the namespace property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setNamespace(Boolean value) {
                this.namespace = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="reject" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="store" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="extract" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reject",
            "store",
            "extract"
        })
        public static class Zip {

            protected boolean reject;
            protected boolean store;
            protected boolean extract;

            /**
             * Gets the value of the reject property.
             * 
             */
            public boolean isReject() {
                return reject;
            }

            /**
             * Sets the value of the reject property.
             * 
             */
            public void setReject(boolean value) {
                this.reject = value;
            }

            /**
             * Gets the value of the store property.
             * 
             */
            public boolean isStore() {
                return store;
            }

            /**
             * Sets the value of the store property.
             * 
             */
            public void setStore(boolean value) {
                this.store = value;
            }

            /**
             * Gets the value of the extract property.
             * 
             */
            public boolean isExtract() {
                return extract;
            }

            /**
             * Sets the value of the extract property.
             * 
             */
            public void setExtract(boolean value) {
                this.extract = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subject"
    })
    public static class Subjects {

        @XmlElement(required = true)
        protected List<String> subject;

        /**
         * Gets the value of the subject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the subject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSubject() {
            if (subject == null) {
                subject = new ArrayList<String>();
            }
            return this.subject;
        }

    }

}
