/* Class name: HelpAbout
 * File name:  HelpAbout.java
 * Project:    Open Document and Information Network (Odin)
 ** Copyright:  © 2007-2012 Alexander J. Harris, all rights reserved
 * Created:    11-Jan-2009 17:27:32
 * Modified:   26-Jul-2010
 *
 * Version History:
 * ~ ~ ~ ~ ~ ~ ~ ~ ~
 * 1.001  26-Jul-2010 Amended for Odin.
 * 1.000  17-Jun-2009 Code finalised and released.
 * 0.001  11-Jan-2009 Initial build
 */

package odin.odin.events.gui;
import java.awt.event.*;
import java.util.logging.*;
import odin.odin.gui.internalframe.Help_About;
import odin.odin.object.logging.*;

/**
 * Listens for events corresponding to any of the three items in the Help menu.
 * An identifier is used to recognise exactly which type of event is being generated.
 * @version 1.001
 * @author Alexander J. Harris (email: Alexander.J.Harris(at)btinternet.com)
 */

public class HelpAbout implements ActionListener
{
  /** The logger to be used for writing messages to the application log */
  private static Logger log;

  /**
   * Creates a new instance of the class. As this class can be used to respond to any one
   * of 3 distinct events the supplied identifier allows us to recognise which event should be triggered.
   * <p> The events supported by this class are:
   * <ul>
   * <li>Help &gt; About</li>
   * <li>Help &gt; Using</li>
   * <li>Help &gt; Licensing</li>
   * </ul>
   * @param identifier The string identifier of the event to be attached to. This should be in lower case.
   */
  public HelpAbout()
  {
    log = LoggerFactory.getLogger(getClass().getName());
  }

  /**
   * The event generate is compared against the button to which it is attached and the
   * appropriate Help window is shown in the GUI.
   * @param e The event generated by the user.
   */
  public void actionPerformed(ActionEvent e)
  {
    Help_About haNew = new Help_About();
  }
}